NUMPY
Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of numpy, focusing on arrays and vectorized operations .

In [2]:
!pip install numpy


In [3]:
import  numpy as np
## create array using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)## 1 row and 5 columns
arr2.shape

(5,)

In [5]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,5]])
print(arr2)
print(arr2.shape)# 2 D array



[[1 2 3 4 5]
 [2 3 4 5 5]]
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape) #output : (2,3)
print("number of dimensions:", arr.ndim) 
print("size (number of elements): ",arr.size)
print("data types:",arr.dtype)
print("item size (in byytes):",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
number of dimensions: 2
size (number of elements):  6
data types: int64
item size (in byytes): 8


In [10]:
### numpy vectorized operation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("add",arr1+arr2)
print("sub",arr1-arr2)
print("mul",arr1*arr2)
print("div",arr1/arr2)

add [11 22 33 44 55]
sub [ -9 -18 -27 -36 -45]
mul [ 10  40  90 160 250]
div [0.1 0.1 0.1 0.1 0.1]


In [11]:
###universal function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

##  exponential
print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
###array slicing and indexing operation 
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[0][0])
print(arr[1:])

1
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [15]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [16]:
### statistical concepts--normalization
## to have a mean of 0 and standard deviation of 1 
data =np.array([1,2,3,4,5])

# calculate the mean and standard deviation 
mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_dev
print("normalized data: ", normalized_data)

normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [17]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean=np.mean(data)
print("mean:",mean)

#meadian
median=np.median(data)
print("median:",median)

#standard deviation
std_dev=np.std(data)
print("standard deviation: ",std_dev)

#variance 
variance=np.var(data)
print("variance:",variance)

mean: 5.5
median: 5.5
standard deviation:  2.8722813232690143
variance: 8.25


In [22]:
#Logical operation 
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data <=8)]


array([5, 6, 7, 8])